spring.application.name=account-service

server.port=8083

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=${ACCOUNT_DB_URL:jdbc:postgresql://localhost:5434/accountdb}
spring.datasource.username=${ACCOUNT_DB_USERNAME:accountuser}
spring.datasource.password=${ACCOUNT_DB_PASSWORD:accountpass}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

spring.kafka.producer.properties.spring.json.add.type.headers=false

# ===============================
# External Services
# ===============================
services.customer.base-url=${CUSTOMER_SERVICE_BASE_URL:http://localhost:8081}

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# ===============================
# Outbox
# ===============================
outbox.processor.fixed-delay-ms=5000