# ===============================
# Application
# ===============================
spring.application.name=customer-service
server.port=8081

# ===============================
# Datasource
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/customerdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:customeruser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:customerpass}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true



# ===============================
# Swagger
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs


# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=customer-service
spring.kafka.consumer.auto-offset-reset=earliest

outbox.processor.fixed-delay-ms=5000


management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
