package com.banking.account.application.error;

public enum ErrorCode {

    ACCOUNT_NOT_FOUND,
    CUSTOMER_NOT_FOUND,

    ACCOUNT_ALREADY_BLOCKED,
    ACCOUNT_ALREADY_ACTIVE,
    ACCOUNT_CLOSED,

    INVALID_ACCOUNT_TYPE,
    INVALID_ACCOUNT_STATUS,
    INVALID_CURRENCY,
    INVALID_BALANCE,

    ACCOUNT_NUMBER_ALREADY_EXISTS,

    BUSINESS_RULE_VIOLATION,
    VALIDATION_ERROR,
    CONFLICT_ERROR
}