# ===============================
# Application
# ===============================
spring.application.name=auth-service

# ===============================
# Datasource
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/authdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:authuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:authpass}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# ===============================
# JWT Configuration
# ===============================
auth.jwt.secret=${AUTH_JWT_SECRET}
auth.jwt.issuer=${AUTH_JWT_ISSUER:auth-service}
auth.jwt.access-ttl-seconds=${AUTH_JWT_ACCESS_TTL_SECONDS:900}
auth.jwt.refresh-ttl-seconds=${AUTH_JWT_REFRESH_TTL_SECONDS:2592000}


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

outbox.processor.fixed-delay-ms=5000


management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
