spring.application.name=audit-service

server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5437/auditdb
spring.datasource.username=audituser
spring.datasource.password=auditpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=audit-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*

audit.topics.user-registered=user.registered
audit.topics.user-logged-in=user-logged-in

audit.topics.customer-created=customer.created

audit.topics.account-created=account.created
audit.topics.account-activated=account.activated
audit.topics.account-blocked=account.blocked
audit.topics.account-debited=account.debited
audit.topics.account-credited=account.credited

audit.topics.transfer-created=transfer.created
audit.topics.transfer-completed=transfer.completed
audit.topics.transfer-failed=transfer.failed

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}