spring.application.name=transaction-service

server.port=8084

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=${TRANSACTION_DB_URL:jdbc:postgresql://localhost:5435/transactiondb}
spring.datasource.username=${TRANSACTION_DB_USERNAME:transactionuser}
spring.datasource.password=${TRANSACTION_DB_PASSWORD:transactionpass}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.consumer.group-id=transaction-service
spring.kafka.consumer.auto-offset-reset=earliest

# ===============================
# Outbox
# ===============================
outbox.processor.fixed-delay-ms=5000

# ===============================
# External Services
# ===============================
services.account.base-url=${ACCOUNT_SERVICE_BASE_URL:http://localhost:8083}

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}