spring.application.name=api-gateway

server.port=8080

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.web.reactive.function.client=INFO

auth.jwt.secret=${AUTH_JWT_SECRET}
auth.jwt.issuer=${AUTH_JWT_ISSUER:auth-service}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}


