
spring.application.name=notification-service

server.port=8085

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5436/notificationdb}
spring.datasource.username=${NOTIFICATION_DB_USERNAME:notificationuser}
spring.datasource.password=${NOTIFICATION_DB_PASSWORD:notificationpass}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.properties.spring.json.add.type.headers=false

# ===============================
# Mail
# ===============================
spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}